// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopFlow.Infrastructure.Data;

#nullable disable

namespace ShopFlow.Migrations
{
    [DbContext(typeof(ShopFlowDbContext))]
    [Migration("20260929134840_Adiconando a tabela Sessão")]
    partial class AdiconandoatabelaSessão
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("CupomId")
                        .HasColumnType("uuid")
                        .HasColumnName("cupom_id");

                    b.Property<string>("TokenAnonimo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_anonimo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carrinhos");

                    b.HasIndex("TokenAnonimo")
                        .IsUnique()
                        .HasDatabaseName("ix_carrinhos_token_anonimo");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_carrinhos_usuario_id");

                    b.ToTable("carrinhos", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_pai_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("CategoriaPaiId")
                        .HasDatabaseName("ix_categorias_categoria_pai_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_slug");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("apelido");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_enderecos_usuario_id");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Estoque", b =>
                {
                    b.Property<Guid>("VarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("variante_id");

                    b.Property<int>("QuantidadeFisica")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_fisica");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_reservada");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("VarianteId")
                        .HasName("pk_estoques");

                    b.ToTable("estoques", null, t =>
                        {
                            t.HasCheckConstraint("ck_estoques_fisica", "quantidade_fisica >= 0");

                            t.HasCheckConstraint("ck_estoques_reservada", "quantidade_reservada >= 0 AND quantidade_reservada <= quantidade_fisica");
                        });
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.ImagemProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid?>("VarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("variante_id");

                    b.HasKey("Id")
                        .HasName("pk_imagens_produto");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_imagens_produto_produto_id");

                    b.HasIndex("VarianteId")
                        .HasDatabaseName("ix_imagens_produto_variante_id");

                    b.ToTable("imagens_produto", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.ItemCarrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrinho_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("VarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("variante_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_carrinho");

                    b.HasIndex("VarianteId")
                        .HasDatabaseName("ix_itens_carrinho_variante_id");

                    b.HasIndex("CarrinhoId", "VarianteId")
                        .IsUnique()
                        .HasDatabaseName("ix_itens_carrinho_carrinho_id_variante_id");

                    b.ToTable("itens_carrinho", null, t =>
                        {
                            t.HasCheckConstraint("ck_itens_carrinho_quantidade", "quantidade BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Marca")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("character varying(170)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_slug");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrada_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sessoes_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessoes_usuario_id");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Variante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Atributos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("atributos");

                    b.Property<int>("PesoGramas")
                        .HasColumnType("integer")
                        .HasColumnName("peso_gramas");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_promocional");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_variantes");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_variantes_produto_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_variantes_sku");

                    b.ToTable("variantes", null, t =>
                        {
                            t.HasCheckConstraint("ck_variantes_preco", "preco > 0");

                            t.HasCheckConstraint("ck_variantes_preco_promocional", "preco_promocional IS NULL OR preco_promocional < preco");
                        });
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Carrinho", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_carrinhos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Categoria", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Categoria", "CategoriaPai")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_categoria_pai_id");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Endereco", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enderecos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Estoque", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Variante", "Variante")
                        .WithOne("Estoque")
                        .HasForeignKey("ShopFlow.Domain.Entidades.Estoque", "VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_variantes_variante_id");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.ImagemProduto", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Produto", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imagens_produto_produtos_produto_id");

                    b.HasOne("ShopFlow.Domain.Entidades.Variante", "Variante")
                        .WithMany()
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_imagens_produto_variantes_variante_id");

                    b.Navigation("Produto");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.ItemCarrinho", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_carrinho_carrinhos_carrinho_id");

                    b.HasOne("ShopFlow.Domain.Entidades.Variante", "Variante")
                        .WithMany()
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_carrinho_variantes_variante_id");

                    b.Navigation("Carrinho");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Produto", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Sessao", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Variante", b =>
                {
                    b.HasOne("ShopFlow.Domain.Entidades.Produto", "Produto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variantes_produtos_produto_id");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Produto", b =>
                {
                    b.Navigation("Imagens");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("ShopFlow.Domain.Entidades.Variante", b =>
                {
                    b.Navigation("Estoque");
                });
#pragma warning restore 612, 618
        }
    }
}
